import { z } from "zod";

export const POLICY_VERSION = "aurelius-fallback-v1";
export const ServerPolicySchema = z.object({ version: z.literal(POLICY_VERSION), provider: z.string().min(1).max(80), region: z.string().min(1).max(80), inputRetentionHours: z.number().int().min(1).max(168), resultRetentionHours: z.number().int().min(1).max(168), auditRetentionDays: z.number().int().min(1).max(365), allowCloudProjectStorage: z.literal(false), maxAssets: z.number().int().min(1).max(100), maxBytes: z.number().int().positive(), maxDurationUs: z.number().int().positive() });
export type ServerPolicy = z.infer<typeof ServerPolicySchema>;
export const DEFAULT_LOCAL_POLICY: ServerPolicy = Object.freeze({ version: POLICY_VERSION, provider: "Aurelius local development renderer", region: "Local machine", inputRetentionHours: 24, resultRetentionHours: 24, auditRetentionDays: 30, allowCloudProjectStorage: false, maxAssets: 30, maxBytes: 2_000_000_000, maxDurationUs: 900_000_000 });
export const FallbackAssetSchema = z.object({ id: z.string().regex(/^[A-Za-z0-9_-]{1,128}$/), fingerprint: z.string().min(8).max(512), byteSize: z.number().int().nonnegative(), mimeType: z.string().min(1).max(160), kind: z.enum(["video", "image", "audio"]), sourcePath: z.string().regex(/^aurelius\/assets\/[A-Za-z0-9._-]+\/original$/) });
export type FallbackAsset = z.infer<typeof FallbackAssetSchema>;
export const FallbackManifestSchema = z.object({ version: z.literal(1), snapshotJobId: z.string().uuid(), projectId: z.string().min(1).max(128), projectRevision: z.number().int().nonnegative(), manifestHash: z.string().regex(/^[a-f0-9]{64}$/), policyVersion: z.literal(POLICY_VERSION), assets: z.array(FallbackAssetSchema).min(1).max(100), dimensions: z.object({ width: z.literal(1080), height: z.union([z.literal(1080), z.literal(1350), z.literal(1920)]) }), frameRate: z.union([z.literal(24), z.literal(30), z.literal(60)]), frameCount: z.number().int().positive(), expectedAudio: z.boolean() });
export type FallbackManifest = z.infer<typeof FallbackManifestSchema>;
export interface FallbackDisclosure { readonly reason: string; readonly policy: ServerPolicy; readonly assets: readonly { readonly id: string; readonly name: string; readonly type: string; readonly bytes: number }[]; readonly manifestHash: string }
export interface ConsentReceipt { readonly manifestHash: string; readonly policyVersion: typeof POLICY_VERSION; readonly confirmedAt: string }
export type FallbackStage = "consenting" | "uploading" | "queued" | "rendering" | "validating" | "ready" | "failed" | "cancelled" | "expired";
export interface FallbackStatus { readonly jobId: string; readonly stage: FallbackStage; readonly progress: number; readonly reason?: "provider-unavailable" | "validation-failed" | "expired" | "cancelled" | "upload-failed" }
export interface JobGrants { readonly jobId: string; readonly upload: Readonly<Record<string, string>>; readonly job: string; readonly result?: string }
export interface BackendArtifact { readonly filename: string; readonly mimeType: "video/mp4"; readonly bytes: Blob }
export interface ServerExportBackend { create(manifest: FallbackManifest, receipt: ConsentReceipt, signal?: AbortSignal): Promise<JobGrants>; upload(jobId: string, assetId: string, grant: string, source: Blob, signal?: AbortSignal): Promise<void>; start(jobId: string, grant: string, signal?: AbortSignal): Promise<void>; status(jobId: string, grant: string, signal?: AbortSignal): Promise<FallbackStatus>; cancel(jobId: string, grant: string): Promise<void>; result(jobId: string, grant: string, signal?: AbortSignal): Promise<BackendArtifact> }
