import type { BackendArtifact, ConsentReceipt, FallbackManifest, FallbackStatus, JobGrants, ServerExportBackend } from "./contracts";
const token = () => crypto.randomUUID().replaceAll("-", "");
type Job = { manifest: FallbackManifest; receipt: ConsentReceipt; upload: Record<string, string>; job: string; result: string; files: Map<string, Blob>; stage: FallbackStatus["stage"]; progress: number };
export class LocalFallbackBackend implements ServerExportBackend {
  private jobs = new Map<string, Job>();
  async create(manifest: FallbackManifest, receipt: ConsentReceipt): Promise<JobGrants> { if (receipt.manifestHash !== manifest.manifestHash) throw new Error("Consent does not match manifest"); const jobId = crypto.randomUUID(); const upload = Object.fromEntries(manifest.assets.map((asset) => [asset.id, token()])); const job = { manifest, receipt, upload, job: token(), result: token(), files: new Map<string, Blob>(), stage: "consenting" as const, progress: 0 }; this.jobs.set(jobId, job); return { jobId, upload, job: job.job, result: job.result }; }
  private get(id: string): Job { const job = this.jobs.get(id); if (!job) throw new Error("Unknown server export"); return job; }
  async upload(jobId: string, assetId: string, grant: string, source: Blob): Promise<void> { const job = this.get(jobId); const expected = job.manifest.assets.find((asset) => asset.id === assetId); if (!expected || job.upload[assetId] !== grant || source.size !== expected.byteSize) throw new Error("Upload was not authorized"); job.stage = "uploading"; job.files.set(assetId, source); job.progress = job.files.size / job.manifest.assets.length; }
  async start(jobId: string, grant: string): Promise<void> { const job = this.get(jobId); if (job.job !== grant || job.files.size !== job.manifest.assets.length) throw new Error("Export cannot start"); job.stage = "rendering"; job.progress = .6; queueMicrotask(() => { if (job.stage === "rendering") { job.stage = "validating"; job.progress = .9; queueMicrotask(() => { if (job.stage === "validating") { job.stage = "ready"; job.progress = 1; } }); } }); }
  async status(jobId: string, grant: string): Promise<FallbackStatus> { const job = this.get(jobId); if (job.job !== grant) throw new Error("Status was not authorized"); return Object.freeze({ jobId, stage: job.stage, progress: job.progress }); }
  async cancel(jobId: string, grant: string): Promise<void> { const job = this.get(jobId); if (grant && job.job !== grant) throw new Error("Cancellation was not authorized"); job.stage = "cancelled"; job.files.clear(); }
  async result(jobId: string, grant: string): Promise<BackendArtifact> { const job = this.get(jobId); if (job.result !== grant || job.stage !== "ready") throw new Error("Result was not authorized"); return { filename: "aurelius-video.mp4", mimeType: "video/mp4", bytes: new Blob([], { type: "video/mp4" }) }; }
}
