import { createHmac, randomUUID, timingSafeEqual } from "node:crypto";
import type { BackendArtifact, ConsentReceipt, FallbackManifest, FallbackStatus, JobGrants } from "@aurelius/export-fallback";

export interface RenderWorker { render(manifest: FallbackManifest, assets: ReadonlyMap<string, Blob>, signal: AbortSignal): Promise<BackendArtifact> }
type Job = { readonly manifest: FallbackManifest; readonly uploads: Map<string, Blob>; readonly controller: AbortController; readonly createdAt: number; stage: FallbackStatus["stage"]; progress: number; artifact?: BackendArtifact; resultGrant?: string };
const b64 = (value: Buffer) => value.toString("base64url");
export class RenderJobService {
  private jobs = new Map<string, Job>();
  constructor(private readonly secret: Buffer, private readonly worker: RenderWorker, private readonly ttlMs = 24 * 60 * 60 * 1000, private readonly now = () => Date.now()) {}
  private grant(jobId: string, action: string, assetId = "") { return b64(createHmac("sha256", this.secret).update(`${jobId}:${action}:${assetId}`).digest()); }
  private valid(jobId: string, action: string, provided: string, assetId = "") { try { const expected = Buffer.from(this.grant(jobId, action, assetId)); const actual = Buffer.from(provided); return actual.length === expected.length && timingSafeEqual(actual, expected); } catch { return false; } }
  private job(jobId: string) { const job = this.jobs.get(jobId); if (!job || this.now() - job.createdAt > this.ttlMs) { if (job) { job.controller.abort(); job.uploads.clear(); job.stage = "expired"; } throw new Error("export-not-found"); } return job; }
  create(manifest: FallbackManifest, receipt: ConsentReceipt): JobGrants { if (receipt.manifestHash !== manifest.manifestHash || receipt.policyVersion !== manifest.policyVersion) throw new Error("consent-mismatch"); const jobId = randomUUID(); const job: Job = { manifest, uploads: new Map(), controller: new AbortController(), createdAt: this.now(), stage: "consenting", progress: 0 }; this.jobs.set(jobId, job); return Object.freeze({ jobId, upload: Object.freeze(Object.fromEntries(manifest.assets.map((asset) => [asset.id, this.grant(jobId, "upload", asset.id)]))), job: this.grant(jobId, "job"), result: this.grant(jobId, "result") }); }
  upload(jobId: string, assetId: string, grant: string, bytes: Blob) { const job = this.job(jobId); const expected = job.manifest.assets.find((asset) => asset.id === assetId); if (!expected || !this.valid(jobId, "upload", grant, assetId) || bytes.size !== expected.byteSize || job.uploads.has(assetId)) throw new Error("upload-denied"); job.stage = "uploading"; job.uploads.set(assetId, bytes); job.progress = job.uploads.size / job.manifest.assets.length; }
  async start(jobId: string, grant: string) { const job = this.job(jobId); if (!this.valid(jobId, "job", grant) || job.uploads.size !== job.manifest.assets.length || job.stage === "rendering") throw new Error("start-denied"); job.stage = "queued"; job.progress = Math.max(job.progress, .5); queueMicrotask(async () => { try { job.stage = "rendering"; job.progress = .65; const artifact = await this.worker.render(job.manifest, job.uploads, job.controller.signal); if (job.controller.signal.aborted) return; if (artifact.mimeType !== "video/mp4") throw new Error("validation-failed"); job.stage = "validating"; job.progress = .9; job.artifact = artifact; job.stage = "ready"; job.progress = 1; } catch { if (!job.controller.signal.aborted) job.stage = "failed"; } }); }
  status(jobId: string, grant: string): FallbackStatus { const job = this.job(jobId); if (!this.valid(jobId, "job", grant)) throw new Error("status-denied"); return Object.freeze({ jobId, stage: job.stage, progress: job.progress, ...(job.stage === "failed" ? { reason: "validation-failed" as const } : {}) }); }
  cancel(jobId: string, grant: string) { const job = this.job(jobId); if (!this.valid(jobId, "job", grant)) throw new Error("cancel-denied"); job.controller.abort(); job.uploads.clear(); job.stage = "cancelled"; job.progress = 0; }
  result(jobId: string, grant: string): BackendArtifact { const job = this.job(jobId); if (!this.valid(jobId, "result", grant) || job.stage !== "ready" || !job.artifact) throw new Error("result-denied"); return job.artifact; }
  purgeExpired() { for (const [id, job] of this.jobs) if (this.now() - job.createdAt > this.ttlMs || ["cancelled", "failed", "expired"].includes(job.stage)) { job.controller.abort(); job.uploads.clear(); this.jobs.delete(id); } }
}
