import { File } from "node:buffer";
import { createProjectDoc, executeCommand, InMemoryProjectRepository } from "@aurelius/project-model";
import { describe, expect, it } from "vitest";
import { InMemoryBinaryStore } from "./binary-store";
import { DexieMediaRepository } from "./media-repository";
import { RelinkService } from "./relink";
import { testDatabase, destroyDatabase } from "./test/indexeddb";
import type { MediaInspector, StoragePolicy, ThumbnailGenerator } from "./types";

const policy:StoragePolicy={inspect:async()=>({ok:true,value:{usage:0,quota:1e9,available:1e9,headroom:1,mode:"persistent"}}),assertCanImport:async()=>({ok:true,value:{usage:0,quota:1e9,available:1e9,headroom:1,mode:"persistent"}}),requestPersistence:async()=>({ok:true,value:{usage:0,quota:1e9,available:1e9,headroom:1,mode:"persistent"}})};
const inspector:MediaInspector={inspect:async(input)=>({ok:true,value:{kind:"image",container:"jpeg",mimeType:"image/jpeg",codecs:[],byteSize:input.size,displayWidth:600,displayHeight:800,support:"ready"}})};const thumbs:ThumbnailGenerator={create:async()=>({ok:true,value:null})};
describe("RelinkService",()=>{it("preserves stable asset identity and creative document",async()=>{let n=0;const base=createProjectDoc({id:"p",title:"P",width:1080,height:1920,frameRate:{numerator:30,denominator:1},nowIso:"2026-09-12T00:00:00.000Z",createId:()=>String(++n)});const registered=executeCommand(base,{type:"asset/register",expectedRevision:0,asset:{id:"asset-old",name:"Missing",kind:"image",mimeType:"image/jpeg",byteSize:1,width:10,height:10,fingerprint:"old"}},{committedAtIso:"2026-09-12T00:01:00.000Z"}).nextDoc;const projects=new InMemoryProjectRepository();await projects.create(registered);const db=testDatabase("relink");const media=new DexieMediaRepository(db);const store=new InMemoryBinaryStore();await media.register({id:"asset-old",displayName:"Missing",fingerprint:"old",kind:"image",container:"jpeg",mimeType:"image/jpeg",codecs:[],byteSize:1,displayWidth:10,displayHeight:10,support:"ready",sourcePath:"aurelius/assets/asset-old/original",state:"missing",createdAt:"2026-09-12T00:00:00.000Z",updatedAt:"2026-09-12T00:00:00.000Z"},"p");const service=new RelinkService(projects,media,store,policy,inspector,thumbs,()=>"2026-09-12T00:02:00.000Z",()=>"token");const result=await service.relink(registered,"asset-old",new File([new Uint8Array([1,2])],"replacement.jpg",{type:"image/jpeg",lastModified:2}));expect(result.ok&&result.value.assets["asset-old"]?.name).toBe("replacement.jpg");expect(result.ok&&result.value.assetOrder).toEqual(["asset-old"]);await destroyDatabase(db);});});
