import { useState } from "react";
import type { ProjectDoc } from "@aurelius/project-model";
import type { TimelineSession } from "../timeline/timeline-session";
import { AureliusCreationSession } from "../aurelius/creation-session";

const createId = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`;
export function AureliusTemplateLauncher({ project, session, writable }: { project: ProjectDoc; session: TimelineSession; writable: boolean }) {
  const [template, setTemplate] = useState<"nuclear-quote" | "hook-reel" | "movie-clip">("hook-reel"); const [hook, setHook] = useState("The obstacle is the way."); const [body, setBody] = useState(""); const [closing, setClosing] = useState("AURELIUS"); const [videoAssetId, setVideoAssetId] = useState(""); const [error, setError] = useState<string>();
  const videos = project.assetOrder.map((id) => project.assets[id]).filter((asset) => asset?.kind === "video"); const launch = () => { try { const input = { template, hook, body, closing, createId, ...(template === "movie-clip" ? { videoAssetId } : {}) } as const; const ok = new AureliusCreationSession(session).compile(input); if (!ok) setError("This first cut could not be added. Check project ownership and try again."); else setError(undefined); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not make this first cut."); } };
  return <section className="aurelius-panel" aria-label="Aurelius first cut"><div><p className="kicker">Aurelius start</p><h2>Make a first cut</h2><p>Choose an intent, then edit every result on the canvas and timeline.</p></div><div className="template-tabs" role="tablist" aria-label="Format"><button role="tab" aria-selected={template === "hook-reel"} onClick={() => setTemplate("hook-reel")}>Hook Reel</button><button role="tab" aria-selected={template === "nuclear-quote"} onClick={() => setTemplate("nuclear-quote")}>Nuclear Quote</button><button role="tab" aria-selected={template === "movie-clip"} onClick={() => setTemplate("movie-clip")}>Movie Clip</button></div><label>Opening thought<textarea value={hook} maxLength={2000} onChange={(event) => setHook(event.target.value)} /></label>{template !== "nuclear-quote" ? <label>Supporting beat <textarea value={body} maxLength={2000} onChange={(event) => setBody(event.target.value)} placeholder="Optional—make the thought land." /></label> : null}{template === "movie-clip" ? <label>Source clip<select value={videoAssetId} onChange={(event) => setVideoAssetId(event.target.value)}><option value="">Choose a project video…</option>{videos.map((asset) => <option key={asset!.id} value={asset!.id}>{asset!.name}</option>)}</select></label> : null}<label>End card<input value={closing} maxLength={200} onChange={(event) => setClosing(event.target.value)} /></label><button className="primary-button" disabled={!writable} onClick={launch}>Create editable first cut</button>{!writable ? <p className="panel-note">Take over editing to create a first cut.</p> : null}{error ? <p className="panel-error" role="alert">{error}</p> : null}</section>;
}
