import { parseCaptionFile, segmentCaptionPhrases, serializeCaptions } from "@aurelius/composition";
import { timeUs, type CaptionCue, type ProjectDoc } from "@aurelius/project-model";
import { useState } from "react";
import type { TimelineSession } from "../timeline/timeline-session";

const id = () => `caption-${globalThis.crypto?.randomUUID?.() ?? Math.random().toString(36).slice(2)}`;
const download = (text: string, name: string) => { const url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 0); };
export function CaptionStudio({ project, session, writable }: { project: ProjectDoc; session: TimelineSession; writable: boolean }) {
  const [script, setScript] = useState(""); const captionTrack = project.trackOrder.map((trackId) => project.tracks[trackId]).find((track) => track?.kind === "caption"); const settings = captionTrack ? project.captionSettings[captionTrack.id] : undefined; const [maxWords, setMaxWords] = useState(settings?.maxWords ?? 8); const [message, setMessage] = useState<string>(); if (!captionTrack || !settings) return null;
  const apply = (source: string) => { const result = segmentCaptionPhrases(source, maxWords, 0, Math.max(3_000_000, ...Object.values(project.clips).map((clip) => clip.startUs + clip.durationUs))); if (!result.ok) { setMessage(result.diagnostics[0]?.message); return; } const cues: CaptionCue[] = result.cues.map((cue) => ({ ...cue, id: id(), trackId: captionTrack.id, textStyleId: settings.defaultTextStyleId })); session.commit({ type: "caption/replaceAll", expectedRevision: project.revision, cues }); session.commit({ type: "caption/setSettings", expectedRevision: session.snapshot.project.revision, trackId: captionTrack.id, maxWords, defaultTextStyleId: settings.defaultTextStyleId }); setMessage(`${cues.length} editable captions added to the timeline.`); };
  const importFile = async (file: File) => { const parsed = parseCaptionFile(await file.text()); if (!parsed.ok) { setMessage(parsed.diagnostics[0]?.message); return; } const cues: CaptionCue[] = parsed.cues.map((cue) => ({ ...cue, id: id(), trackId: captionTrack.id, textStyleId: settings.defaultTextStyleId })); session.commit({ type: "caption/replaceAll", expectedRevision: project.revision, cues }); setMessage(`${cues.length} cues imported.`); };
  return <section className="aurelius-panel caption-studio" aria-label="Caption studio"><div><p className="kicker">Spoken words</p><h2>Caption studio</h2></div><label>Paste a script<textarea value={script} onChange={(event) => setScript(event.target.value)} placeholder="One useful thought, at a time." /></label><label>Maximum words <input type="range" min="1" max="20" value={maxWords} onChange={(event) => setMaxWords(Number(event.target.value))} /><output>{maxWords}</output></label><div className="caption-actions"><button disabled={!writable || !script.trim()} onClick={() => apply(script)}>Build editable captions</button><label className="file-button">Import SRT/VTT<input type="file" accept=".srt,.vtt,text/vtt,text/plain" disabled={!writable} onChange={(event) => { const file = event.target.files?.[0]; if (file) void importFile(file); event.currentTarget.value = ""; }} /></label><button onClick={() => download(serializeCaptions(Object.values(project.captionCues), "srt"), `${project.title}.srt`)}>Export SRT</button><button onClick={() => download(serializeCaptions(Object.values(project.captionCues), "vtt"), `${project.title}.vtt`)}>Export VTT</button></div>{message ? <p className="panel-note" role="status">{message}</p> : null}</section>;
}
