import { useEffect, useMemo, useRef, useState } from "react";
import { alignmentTargets, evaluateFrame, type ResolvedLayer } from "@aurelius/composition";
import { timeUsToFrameIndex, type Clip, type ProjectDoc, type Transform } from "@aurelius/project-model";
import type { AppRuntime } from "../runtime";
import type { TimelineSession } from "../timeline/timeline-session";
import { CanvasInspector } from "./CanvasInspector";
import { CompositionPreview } from "./CompositionPreview";
import { InlineTextEditor } from "./InlineTextEditor";
import "./canvas.css";

type Gesture = { readonly mode: "move" | "resize" | "rotate"; readonly originX: number; readonly originY: number; readonly transform: Transform; readonly layer: ResolvedLayer };
const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

function useSessionFrame(session: TimelineSession | null) { const [frame, setFrame] = useState(0); useEffect(() => session ? session.subscribe((snapshot) => setFrame(timeUsToFrameIndex(snapshot.playheadUs as never, snapshot.project.composition.frameRate, "nearest"))) : undefined, [session]); return frame; }

export function CompositionCanvas({ runtime, project, session, writable, showInsertControls = true }: { runtime: AppRuntime; project: ProjectDoc; session: TimelineSession | null; writable: boolean; showInsertControls?: boolean }) {
  const [selectedId, setSelectedId] = useState<string>(); const [safeAreas, setSafeAreas] = useState(true); const [editingId, setEditingId] = useState<string>(); const [gesture, setGesture] = useState<Gesture>(); const [previewTransform, setPreviewTransform] = useState<Transform>(); const [guide, setGuide] = useState<{ axis: "x" | "y"; value: number }>(); const rootRef = useRef<HTMLDivElement>(null); const frameIndex = useSessionFrame(session);
  const frame = useMemo(() => evaluateFrame(project, frameIndex), [project, frameIndex]); const selectedLayer = frame.layers.find((layer) => layer.id === selectedId); const selected = selectedId ? project.clips[selectedId] : undefined;
  useEffect(() => { if (selectedId && !project.clips[selectedId]) setSelectedId(undefined); }, [project, selectedId]);
  const choose = (id?: string) => { setEditingId(undefined); setSelectedId(id); session?.select(id); };
  const eventPoint = (event: React.PointerEvent) => { const rect = rootRef.current!.getBoundingClientRect(); return { x: (event.clientX - rect.left) / rect.width * 1080, y: (event.clientY - rect.top) / rect.height * project.composition.height }; };
  const begin = (event: React.PointerEvent, mode: Gesture["mode"]) => { if (!selectedLayer || !selected || !writable) return; event.preventDefault(); event.stopPropagation(); const point = eventPoint(event); (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); setGesture({ mode, originX: point.x, originY: point.y, transform: selectedLayer.transform, layer: selectedLayer }); };
  const move = (event: React.PointerEvent) => { if (!gesture || !rootRef.current) return; const point = eventPoint(event); const dx = point.x - gesture.originX; const dy = point.y - gesture.originY; let next: Transform = gesture.transform;
    if (gesture.mode === "move") { let x = gesture.transform.x + dx / 1080; let y = gesture.transform.y + dy / project.composition.height; if (!event.altKey) { const others = frame.layers.filter((layer) => layer.id !== gesture.layer.id); const targets = alignmentTargets(project.composition.height, others); const centerX = x * 1080; const centerY = y * project.composition.height; const xTarget = targets.filter((target) => target.axis === "x").find((target) => Math.abs(target.value - centerX) < 12); const yTarget = targets.filter((target) => target.axis === "y").find((target) => Math.abs(target.value - centerY) < 12); if (xTarget) { x = xTarget.value / 1080; setGuide({ axis: "x", value: xTarget.value }); } else if (yTarget) { y = yTarget.value / project.composition.height; setGuide({ axis: "y", value: yTarget.value }); } else setGuide(undefined); } next = { ...gesture.transform, x: clamp(x, -1, 2), y: clamp(y, -1, 2) }; }
    if (gesture.mode === "resize") { const factor = clamp(1 + (dx + dy) / 720, .05, 8); next = { ...gesture.transform, scaleX: clamp(gesture.transform.scaleX * factor, .05, 8), scaleY: clamp(gesture.transform.scaleY * factor, .05, 8) }; }
    if (gesture.mode === "rotate") { const angle = Math.atan2(point.y - gesture.layer.bounds.y - gesture.layer.bounds.height / 2, point.x - gesture.layer.bounds.x - gesture.layer.bounds.width / 2) * 180 / Math.PI; next = { ...gesture.transform, rotationDeg: Math.round(angle) }; }
    setPreviewTransform(next);
  };
  const end = () => { if (gesture && previewTransform && selected && session) session.commit({ type: "clip/setTransform", expectedRevision: project.revision, clipId: selected.id, transform: previewTransform }); setGesture(undefined); setPreviewTransform(undefined); setGuide(undefined); };
  const layerTransform = previewTransform && selectedLayer ? { ...selectedLayer.transform, ...previewTransform } : selectedLayer?.transform;
  const visualBounds = selectedLayer && layerTransform ? { width: selectedLayer.bounds.width * (layerTransform.scaleX / selectedLayer.transform.scaleX), height: selectedLayer.bounds.height * (layerTransform.scaleY / selectedLayer.transform.scaleY), x: layerTransform.x * 1080 - selectedLayer.bounds.width * (layerTransform.scaleX / selectedLayer.transform.scaleX) / 2, y: layerTransform.y * project.composition.height - selectedLayer.bounds.height * (layerTransform.scaleY / selectedLayer.transform.scaleY) / 2 } : undefined;
  const setFormat = (height: 1920 | 1350 | 1080) => session?.commit({ type: "composition/setFormat", expectedRevision: project.revision, height });
  const setCrop = (mode: "fit" | "fill" | "blur") => { if (selected && (selected.kind === "image" || selected.kind === "video")) session?.commit({ type: "clip/setCrop", expectedRevision: project.revision, clipId: selected.id, crop: { mode, x: selected.crop?.x ?? 0, y: selected.crop?.y ?? 0, zoom: selected.crop?.zoom ?? 1 } }); };
  const setLayer = (delta: number) => { if (selected) session?.commit({ type: "clip/setLayer", expectedRevision: project.revision, clipId: selected.id, layer: clamp(selected.layer + delta, 0, 99) }); };
  const adjustCrop = (axis: "x" | "y" | "zoom", amount: number) => { if (!selected || (selected.kind !== "image" && selected.kind !== "video")) return; const crop = { mode: selected.crop?.mode ?? "fill", x: selected.crop?.x ?? 0, y: selected.crop?.y ?? 0, zoom: selected.crop?.zoom ?? 1 }; if (axis === "x") crop.x = clamp(crop.x + amount, -1, 1); if (axis === "y") crop.y = clamp(crop.y + amount, -1, 1); if (axis === "zoom") crop.zoom = clamp(crop.zoom + amount, .1, 10); session?.commit({ type: "clip/setCrop", expectedRevision: project.revision, clipId: selected.id, crop }); };
  const addText = (role: "heading" | "quote" | "label" | "credit" | "body") => { session?.addText(role); };
  const editText = () => { if (selected?.kind === "text") setEditingId(selected.id); };
  return <section className="canvas-editor" aria-label="Aurelius composition canvas"><div ref={rootRef} className="canvas-shell" onPointerDown={(event) => { if (event.target === event.currentTarget) choose(); }} onPointerMove={move} onPointerUp={end} onPointerCancel={() => { setGesture(undefined); setPreviewTransform(undefined); setGuide(undefined); }}>
    <CompositionPreview runtime={runtime} project={project} frameIndex={frameIndex} showSafeAreas={false} />
    <div className="canvas-overlay" onPointerDown={(event) => { if (event.target === event.currentTarget) choose(); }}>
      {safeAreas ? <><div className="canvas-safe" style={{ left: `${frame.safeAreas.content.x / 10.8}%`, top: `${frame.safeAreas.content.y / project.composition.height * 100}%`, width: `${frame.safeAreas.content.width / 10.8}%`, height: `${frame.safeAreas.content.height / project.composition.height * 100}%` }} /><div className="canvas-safe bottom" style={{ left: `${frame.safeAreas.bottomUi.x / 10.8}%`, top: `${frame.safeAreas.bottomUi.y / project.composition.height * 100}%`, width: `${frame.safeAreas.bottomUi.width / 10.8}%` }} /></> : null}
      {guide ? <div className={`canvas-guide ${guide.axis}`} style={guide.axis === "x" ? { left: `${guide.value / 10.8}%` } : { top: `${guide.value / project.composition.height * 100}%` }} /> : null}
      {frame.layers.map((layer) => <button key={layer.id} className="canvas-hitbox" aria-label={`Select ${layer.kind} layer`} style={{ left: `${layer.bounds.x / 10.8}%`, top: `${layer.bounds.y / project.composition.height * 100}%`, width: `${layer.bounds.width / 10.8}%`, height: `${layer.bounds.height / project.composition.height * 100}%` }} onClick={(event) => { event.stopPropagation(); choose(layer.id); if (layer.kind === "text") setEditingId(layer.id); }} />)}
      {selectedLayer && visualBounds ? <div className="canvas-selection" role="button" aria-label={`Selected ${selectedLayer.kind} layer`} tabIndex={0} style={{ left: `${visualBounds.x / 10.8}%`, top: `${visualBounds.y / project.composition.height * 100}%`, width: `${visualBounds.width / 10.8}%`, height: `${visualBounds.height / project.composition.height * 100}%`, transform: `rotate(${layerTransform?.rotationDeg ?? 0}deg)` }} onDoubleClick={editText} onPointerDown={(event) => begin(event, "move")} onKeyDown={(event) => { if (!selected || !session) return; const amount = event.shiftKey ? 10 : 1; const delta = event.key === "ArrowLeft" ? [-amount, 0] : event.key === "ArrowRight" ? [amount, 0] : event.key === "ArrowUp" ? [0, -amount] : event.key === "ArrowDown" ? [0, amount] : null; if (delta) { event.preventDefault(); session.commit({ type: "clip/setTransform", expectedRevision: project.revision, clipId: selected.id, transform: { ...selectedLayer.transform, x: selectedLayer.transform.x + (delta[0] ?? 0) / 1080, y: selectedLayer.transform.y + (delta[1] ?? 0) / project.composition.height } }); } if (event.key === "Enter") editText(); }}><i className="canvas-handle resize" aria-label="Resize" onPointerDown={(event) => begin(event, "resize")} /><i className="canvas-handle rotate" aria-label="Rotate" onPointerDown={(event) => begin(event, "rotate")} /></div> : null}
      {editingId && selectedLayer && selected?.kind === "text" ? <InlineTextEditor layer={selectedLayer} canvasHeight={project.composition.height} initialValue={selected.content} onCancel={() => setEditingId(undefined)} onCommit={(content) => { if (content.trim() && content !== selected.content) session?.commit({ type: "text/setContent", expectedRevision: project.revision, clipId: selected.id, content }); setEditingId(undefined); }} /> : null}
      {!selectedLayer && !editingId ? <button className="canvas-hit-layer" aria-label="Select topmost layer" style={{ position: "absolute", inset: 0, opacity: 0, border: 0 }} onClick={(event) => { event.stopPropagation(); choose(frame.layers.at(-1)?.id); }} /> : null}
    </div>
  </div><CanvasInspector project={project} {...(selected ? { selected } : {})} writable={writable} safeAreas={safeAreas} onSafeAreas={setSafeAreas} onFormat={(height) => { setFormat(height); }} onCrop={setCrop} onCropAdjust={adjustCrop} onLayer={setLayer} />{showInsertControls ? <div className="canvas-insert" aria-label="Add canvas text"><button disabled={!writable} onClick={() => addText("heading")}>+ Heading</button><button disabled={!writable} onClick={() => addText("quote")}>+ Quote</button><button disabled={!writable} onClick={() => addText("label")}>+ Label</button><button disabled={!writable} onClick={() => addText("credit")}>+ Credit</button><button disabled={!writable} onClick={() => addText("body")}>+ Body</button></div> : null}</section>;
}
