import { useEffect, useRef, useState } from "react";
import type { AppRuntime } from "../runtime";
import type { StoredMediaAsset } from "@aurelius/media";

const bytes = (value: number) => value < 1024 ? `${value} B` : value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 ** 2).toFixed(1)} MB`;
const duration = (value?: number) => value === undefined ? null : `${Math.floor(value / 60_000_000)}:${String(Math.round(value / 1_000_000) % 60).padStart(2, "0")}`;
export function MediaCard({ runtime, asset, onRename, onReplace, onRemove, onPlace, compact = false }: { runtime: AppRuntime; asset: StoredMediaAsset; onRename(name: string): Promise<void>; onReplace(file: File): Promise<void>; onRemove(): Promise<void>; onPlace?: ((assetId: string) => void) | undefined; compact?: boolean }) {
  const [url, setUrl] = useState<string | null>(null); const [editing, setEditing] = useState(false); const [name, setName] = useState(asset.displayName); const replacement = useRef<HTMLInputElement>(null);
  useEffect(() => { let active = true; let release = () => {}; if (asset.posterPath) void runtime.resources.acquire(asset.id, asset.updatedAt, asset.posterPath).then((lease) => { release = lease.release; if (active) setUrl(lease.url); else lease.release(); }).catch(() => {}); return () => { active = false; release(); }; }, [asset, runtime]);
  return <article className={`media-card${compact ? " compact-media-card" : ""}`}><div className={`media-poster ${asset.kind}`}>{url ? <img src={url} alt="" /> : <span aria-hidden="true">{asset.kind === "video" ? "▶" : asset.kind === "audio" ? "♪" : "▧"}</span>}{asset.state === "missing" ? <b>Missing</b> : null}</div><div className="media-copy">{editing ? <form onSubmit={(event) => { event.preventDefault(); void onRename(name).then(() => setEditing(false)); }}><label>Media name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label><button>Save</button></form> : <strong title={asset.displayName}>{asset.displayName}</strong>}<p>{asset.kind} · {duration(asset.durationUs) ? duration(asset.durationUs) : asset.displayWidth ? `${asset.displayWidth}×${asset.displayHeight}` : "still"}</p>{!compact ? <small>{bytes(asset.byteSize)} · {asset.codecs.join(" + ") || "still image"} · {asset.support}</small> : null}</div><div className="media-actions">{onPlace ? <button disabled={asset.state !== "ready" || asset.support !== "ready"} title={asset.state !== "ready" ? "Relink this source first" : undefined} onClick={() => onPlace(asset.id)}>{compact ? "+ Add" : "Add to timeline"}</button> : null}{!compact ? <><button onClick={() => setEditing(!editing)}>Rename</button><input ref={replacement} hidden type="file" accept={`${asset.kind}/*`} onChange={(event) => { const file = event.target.files?.[0]; if (file) void onReplace(file); event.currentTarget.value = ""; }} /><button onClick={() => replacement.current?.click()}>{asset.state === "missing" ? "Relink" : "Replace"}</button><button className="danger-link" onClick={() => { if (confirm(`Remove ${asset.displayName} from this project?`)) void onRemove(); }}>Remove</button></> : null}</div></article>;
}
