import type { ProjectDoc } from "@aurelius/project-model";
import type { AppRuntime } from "../runtime";
import type { AutosaveCoordinator } from "@aurelius/media";
import { useMediaLibrary } from "../hooks/useMediaLibrary";
import { ImportDropzone } from "./ImportDropzone"; import { MediaCard } from "./MediaCard"; import { StorageStatus } from "./StorageStatus"; import { ManifestControls } from "./ManifestControls"; import { MissingMediaPanel } from "./MissingMediaPanel"; import "./media-library.css";

export function MediaLibrary({ runtime, project, onProjectChange, autosave, onPlaceAsset, compact = false }: { runtime: AppRuntime; project: ProjectDoc; onProjectChange(project: ProjectDoc): void; autosave: AutosaveCoordinator | null; onPlaceAsset?(assetId: string): void; compact?: boolean }) {
  const library = useMediaLibrary(runtime, project, onProjectChange, autosave);
  return <aside className={`library-panel${compact ? " compact-library" : ""}`}>{compact ? <div className="library-heading compact-heading"><span>{library.assets.length}</span><small>Click <b>Add</b> to place an item at the end of your film.</small></div> : <div className="library-heading"><div><p className="kicker">Project media</p><h2>Library</h2></div><span>{library.assets.length}</span></div>}<ImportDropzone onFiles={library.importFiles} />{library.progress.some((item) => item.stage !== "ready") ? <div className="import-progress" aria-live="polite">{library.progress.filter((item) => item.stage !== "ready").map((item) => <div key={item.importId}><span>{item.stage}</span><progress max={item.totalBytes} value={item.bytesCopied} /></div>)}</div> : null}{library.errors.map((error) => <div key={error.diagnosticId} className="media-error" role="alert"><strong>{error.message}</strong><p>{error.recoveryAction.replaceAll("-", " ")}</p><small>{error.diagnosticId}</small></div>)}<MissingMediaPanel items={library.missing} onRelink={library.replace} />{library.loading ? <p>Reading media…</p> : library.assets.length === 0 ? <div className="library-empty"><strong>Your sources will live here.</strong><p>Add raw clips, photographs, music, or narration to start shaping your edit.</p></div> : <div className="media-grid">{library.assets.map((asset) => <MediaCard key={asset.id} runtime={runtime} asset={asset} onRename={(name) => library.rename(asset.id, name)} onReplace={(file) => library.replace(asset.id, file)} onRemove={() => library.remove(asset.id)} onPlace={onPlaceAsset} compact={compact} />)}</div>}{!compact ? <><StorageStatus storage={library.storage} onPersist={library.requestPersistence} /><ManifestControls runtime={runtime} project={project} onImported={() => { window.location.reload(); }} /></> : null}</aside>;
}
