import { useEffect, useRef, useState } from "react";
import { executeCommand, type ProjectDoc } from "@aurelius/project-model";
import type { AutosaveCoordinator, AutosaveState, OwnershipStatus } from "@aurelius/media";
import type { AppRuntime } from "../runtime";
import { SaveStatus } from "./SaveStatus";
import { MediaLibrary } from "./MediaLibrary";
import { TimelineEditor } from "./TimelineEditor";
import { CompositionCanvas } from "./CompositionCanvas";
import type { TimelineSession } from "../timeline/timeline-session";
import "./aurelius-creation.css";
import { StudioSidebar } from "./StudioSidebar";
import "./studio-workspace.css";

export function ProjectWorkspace({ runtime, projectId, onBack }: { runtime: AppRuntime; projectId: string; onBack(): void }) {
  const [project, setProject] = useState<ProjectDoc | null>(null); const [save, setSave] = useState<AutosaveState | null>(null); const [ownership, setOwnership] = useState<OwnershipStatus>(runtime.ownership.snapshot); const [error, setError] = useState<string | null>(null); const [canvasSession, setCanvasSession] = useState<TimelineSession | null>(null); const autosave = useRef<AutosaveCoordinator | null>(null); const timeline = useRef<TimelineSession | null>(null);
  useEffect(() => { let active = true; let unsubscribeSave = () => {}; const unsubscribeOwnership = runtime.ownership.subscribe(setOwnership); void (async () => { try { const doc = await runtime.projectService.open(projectId); if (!doc) throw new Error("Project not found"); await runtime.ownership.acquire(projectId); if (!active) return; const coordinator = runtime.createAutosave(doc); autosave.current = coordinator; unsubscribeSave = coordinator.subscribe((state) => { if (active) setSave(state); }); setProject(doc); } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : "Could not open project"); } })(); return () => { active = false; timeline.current?.dispose(); timeline.current = null; unsubscribeSave(); unsubscribeOwnership(); void autosave.current?.dispose(); void runtime.ownership.release(); }; }, [projectId, runtime]);
  const rename = (title: string) => { if (!project || !ownership.writable) return; try { const next = executeCommand(project, { type: "project/rename", expectedRevision: project.revision, title }, { committedAtIso: new Date().toISOString() }).nextDoc; setProject(next); autosave.current?.submit(next); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not rename"); } };
  const back = async () => { await autosave.current?.flush(); await runtime.ownership.release(); onBack(); };
  if (error) return <main className="workspace-error"><h1>Project needs attention</h1><p>{error}</p><button onClick={onBack}>Back to projects</button></main>;
  if (!project) return <main className="workspace-loading" role="status">Opening project…</main>;
  return <main className="workspace-shell studio-workspace"><header className="workspace-header studio-header"><button className="back-button" onClick={() => void back()}>← Library</button><span className="studio-mark">A</span><label className="workspace-title"><span>Film title</span><input value={project.title} disabled={!ownership.writable} onChange={(event) => rename(event.target.value)} /></label><div className="workspace-history"><button disabled={!timeline.current?.snapshot.undoLabel || !ownership.writable} title={timeline.current?.snapshot.undoLabel ? `Undo ${timeline.current.snapshot.undoLabel}` : "Nothing to undo"} onClick={() => timeline.current?.undo()}>↶ Undo</button><button disabled={!timeline.current?.snapshot.redoLabel || !ownership.writable} title={timeline.current?.snapshot.redoLabel ? `Redo ${timeline.current.snapshot.redoLabel}` : "Nothing to redo"} onClick={() => timeline.current?.redo()}>Redo ↷</button></div><SaveStatus save={save} ownership={ownership} onRetry={() => void autosave.current?.retry()} onRestore={() => void autosave.current?.restoreLatest().then((doc) => doc && setProject(doc))} />{ownership.mode === "read-only" ? <button className="takeover" onClick={() => { if (confirm("Take over editing? The other tab will become read-only and stale saves will still be rejected.")) void runtime.ownership.takeOver(); }}>Take over</button> : null}</header><div className="studio-edit-area"><aside className="studio-media"><div className="studio-panel-heading"><p className="kicker">Your ingredients</p><h2>Media</h2><span>Drag in clips, photos, music.</span></div><MediaLibrary compact runtime={runtime} project={project} onProjectChange={setProject} autosave={autosave.current} onPlaceAsset={(assetId) => timeline.current?.addAsset(assetId)} /></aside><section className="studio-stage"><div className="studio-stage-bar"><span>Live preview</span><small>Click text to write directly on the canvas. Drag any layer to place it.</small></div><CompositionCanvas runtime={runtime} project={project} session={canvasSession} writable={ownership.writable} showInsertControls={false} /></section>{canvasSession ? <StudioSidebar project={project} session={canvasSession} writable={ownership.writable} /> : <aside className="studio-sidebar loading-tools">Preparing tools…</aside>}</div><TimelineEditor project={project} autosave={autosave.current} writable={ownership.writable} onProjectChange={setProject} onSession={(session) => { timeline.current = session; setCanvasSession(session); }} /></main>;
}
