import type { ProjectDoc } from "@aurelius/project-model";
import type { TimelineSession } from "../timeline/timeline-session";
import { timeUs } from "@aurelius/project-model";
import { AudioInspector } from "./AudioInspector";
const id = () => `source-${globalThis.crypto?.randomUUID?.() ?? Math.random().toString(36).slice(2)}`;
export function TimelineInspector({ project, selectedId, session, writable }: { project: ProjectDoc; selectedId?: string | undefined; session: TimelineSession; writable: boolean }) {
  const caption = selectedId ? project.captionCues[selectedId] : undefined; const clip = selectedId ? project.clips[selectedId] : undefined;
  if (caption) return <aside className="timeline-inspector" aria-label="Caption inspector"><p className="kicker">Selected caption</p><textarea value={caption.text} disabled={!writable} onChange={(event) => session.commit({ type: "caption/update", expectedRevision: project.revision, cueId: caption.id, text: event.target.value })} /><label>Placement<select value={caption.position} disabled={!writable} onChange={(event) => session.commit({ type: "caption/update", expectedRevision: project.revision, cueId: caption.id, position: event.target.value as "lower" | "center" })}><option value="lower">Lower safe zone</option><option value="center">Center</option></select></label><label>Start (seconds)<input type="number" step=".1" value={caption.startUs / 1e6} disabled={!writable} onChange={(event) => session.commit({ type: "caption/setTiming", expectedRevision: project.revision, cueId: caption.id, startUs: timeUs(Math.round(Number(event.target.value) * 1e6)), endUs: caption.endUs })} /></label></aside>;
  if (!clip) return <aside className="timeline-inspector"><p className="kicker">Inspector</p><strong>Select a clip</strong><p>Trim, split, duplicate, layer, sound, and caption controls appear here.</p></aside>; const locked = project.tracks[clip.trackId]?.locked ?? true; const run = (callback: () => void) => { if (writable && !locked) callback(); };
  const addSource = () => { const audioTrack = project.trackOrder.map((trackId) => project.tracks[trackId]).find((track) => track?.kind === "audio"); if (!audioTrack || clip.kind !== "video") return; session.commit({ type: "audio/addSourceFromVideo", expectedRevision: project.revision, clip: { id: id(), kind: "audio", role: "source", trackId: audioTrack.id, startUs: clip.startUs, durationUs: clip.durationUs, layer: 0, enabled: true, assetId: clip.assetId, sourceInUs: clip.sourceInUs, sourceDurationUs: clip.sourceDurationUs, muted: false, volume: 1, fadeInUs: timeUs(0), fadeOutUs: timeUs(0) } }); };
  return <aside className="timeline-inspector" aria-label="Selected clip inspector"><p className="kicker">Selected {clip.kind}{clip.kind === "audio" ? ` · ${clip.role}` : ""}</p><strong>{clip.kind === "text" ? clip.content : project.assets[clip.assetId]?.name ?? clip.assetId}</strong><dl><div><dt>Starts</dt><dd>{(clip.startUs / 1e6).toFixed(2)} s</dd></div><div><dt>Duration</dt><dd>{(clip.durationUs / 1e6).toFixed(2)} s</dd></div><div><dt>Layer</dt><dd>{clip.layer}</dd></div></dl><div className="inspector-actions"><button disabled={!writable || locked} title={locked ? "Unlock this lane first" : undefined} onClick={() => run(() => session.splitSelected())}>Split</button><button disabled={!writable || locked} onClick={() => run(() => session.duplicateSelected())}>Duplicate</button><button disabled={!writable || locked} onClick={() => run(() => session.deleteSelected())}>Delete</button><button disabled={!writable || locked} onClick={() => run(() => session.deleteSelected(true))}>Ripple delete</button>{clip.kind === "video" ? <button disabled={!writable} onClick={addSource}>Add source sound</button> : null}</div><label>Layer<input type="number" min="0" max="99" value={clip.layer} disabled={!writable || locked} onChange={(event) => session.commit({ type: "timeline/reorderLayer", expectedRevision: project.revision, clipId: clip.id, layer: Number(event.target.value) })} /></label>{clip.kind === "audio" ? <AudioInspector project={project} clip={clip} session={session} writable={writable && !locked} /> : null}</aside>;
}
