import { timeUs, type CaptionCue } from "@aurelius/project-model";

export const CAPTION_LIMITS = { maxBytes: 200_000, maxCues: 250, maxWords: 20 } as const;
export interface CaptionDiagnostic { readonly message: string; readonly line?: number; }
export type CaptionResult = { readonly ok: true; readonly cues: readonly Omit<CaptionCue, "id" | "trackId" | "textStyleId">[] } | { readonly ok: false; readonly diagnostics: readonly CaptionDiagnostic[] };
const clean = (value: string) => value.replace(/<[^>]*>/gu, "").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/gu, " ").replace(/\s+/gu, " ").trim();
const timestamp = (value: string): number | null => { const match = value.trim().match(/^(?:(\d{1,2}):)?(\d{2}):(\d{2})[,.](\d{3})$/u); if (!match) return null; const [, h = "0", m, s, ms] = match; const result = ((Number(h) * 3600 + Number(m) * 60 + Number(s)) * 1000 + Number(ms)) * 1000; return Number.isSafeInteger(result) ? result : null; };
export function segmentCaptionPhrases(script: string, maxWords: number, startUs: number, endUs: number): CaptionResult {
  if (!script.trim() || script.length > CAPTION_LIMITS.maxBytes || !Number.isInteger(maxWords) || maxWords < 1 || maxWords > CAPTION_LIMITS.maxWords || endUs <= startUs) return { ok: false, diagnostics: [{ message: "Use a short script, 1–20 words per cue, and a positive timeline range." }] };
  const sentences = script.replace(/\r\n?/gu, "\n").split(/(?<=[.!?])\s+|\n+/u).flatMap((sentence) => { const words = clean(sentence).split(" ").filter(Boolean); const groups: string[] = []; for (let i = 0; i < words.length; i += maxWords) groups.push(words.slice(i, i + maxWords).join(" ")); return groups; }).filter(Boolean);
  if (!sentences.length || sentences.length > CAPTION_LIMITS.maxCues) return { ok: false, diagnostics: [{ message: "Caption input produces too many or no cues." }] };
  const span = endUs - startUs; return { ok: true, cues: sentences.map((text, index) => ({ startUs: timeUs(Math.round(startUs + span * index / sentences.length)), endUs: timeUs(Math.round(startUs + span * (index + 1) / sentences.length)), text, emphasisWordIndexes: [], position: "lower" })) };
}
export function parseCaptionFile(source: string): CaptionResult {
  if (source.length > CAPTION_LIMITS.maxBytes) return { ok: false, diagnostics: [{ message: "Caption file is too large." }] }; const lines = source.replace(/^\uFEFF/u, "").replace(/\r\n?/gu, "\n").split("\n"); const cues: Omit<CaptionCue, "id" | "trackId" | "textStyleId">[] = []; let index = 0; if (lines[0]?.trim() === "WEBVTT") index = 1;
  while (index < lines.length) { while (!lines[index]?.trim()) index++; if (index >= lines.length) break; if (!lines[index]?.includes("-->")) index++; const timing = lines[index++]; const match = timing?.match(/^\s*([^\s]+)\s+-->\s+([^\s]+)(?:\s+(.*))?$/u); if (!match) return { ok: false, diagnostics: [{ message: "Expected a caption timestamp line.", line: index }] }; const start = timestamp(match[1]!); const end = timestamp(match[2]!); const settings = match[3]?.trim(); if (start === null || end === null || end <= start || (settings && !/^(line:(?:\d+|\d+%)|position:(?:\d+|\d+%))$/u.test(settings))) return { ok: false, diagnostics: [{ message: "Caption timing or settings are unsupported.", line: index }] }; const content: string[] = []; while (index < lines.length && lines[index]?.trim()) content.push(lines[index++]!); const text = clean(content.join(" ")); if (!text) return { ok: false, diagnostics: [{ message: "Caption text is empty.", line: index }] }; cues.push({ startUs: timeUs(start), endUs: timeUs(end), text, emphasisWordIndexes: [], position: settings?.startsWith("position:50") ? "center" : "lower" }); if (cues.length > CAPTION_LIMITS.maxCues) return { ok: false, diagnostics: [{ message: "Too many cues." }] }; }
  for (let i = 1; i < cues.length; i++) if (cues[i - 1]!.endUs > cues[i]!.startUs) return { ok: false, diagnostics: [{ message: "Caption cues overlap." }] }; return cues.length ? { ok: true, cues } : { ok: false, diagnostics: [{ message: "No caption cues found." }] };
}
const format = (us: number, vtt: boolean) => { const total = Math.round(us / 1000); const hours = Math.floor(total / 3_600_000); const minutes = Math.floor(total / 60_000) % 60; const seconds = Math.floor(total / 1000) % 60; const milliseconds = total % 1000; return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}${vtt ? "." : ","}${String(milliseconds).padStart(3, "0")}`; };
export function serializeCaptions(cues: readonly CaptionCue[], formatType: "srt" | "vtt"): string { const vtt = formatType === "vtt"; const body = [...cues].sort((a,b) => a.startUs - b.startUs || a.id.localeCompare(b.id)).map((cue, index) => `${vtt ? "" : `${index + 1}\n`}${format(cue.startUs, vtt)} --> ${format(cue.endUs, vtt)}${vtt && cue.position === "center" ? " position:50%" : ""}\n${cue.text}`).join("\n\n"); return vtt ? `WEBVTT\n\n${body}\n` : `${body}\n`; }
